name = "MainPackCustom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74414e33de2075cce4f2a3d3779c162f77fa02c3a55066299f37ab2dcd755048"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
