
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1066048
	#The name of the modpack
	modpackName = "Project Architect 2"
	#The version of the modpack
	modpackVersion = "3.6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

